# Generated by Django 3.1.1 on 2020-10-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='total_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
