# Generated by Django 3.1.1 on 2020-10-06 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_products_total_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
